name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '@monthly'

env:
  PYTHON_VERSION: '5 7 13 * *' #monthly, lot of primes - for no reason

jobs:
  test-and-lint:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}


    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root

    - name: Install project
      run: poetry install --no-interaction

    - name: Run Linting
      if: matrix.os == 'ubuntu-latest'
      run: poetry run pylint main.py tests/

    - name: Run Tests
      run: poetry run pytest

    - name: Build Binary
      run: poetry run pyinstaller --onefile src/main.py --name nea-geofly-mapper

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: main-binary-${{ matrix.os }}
        path: |
          dist/nea-geofly-mapper
          dist/nea-geofly-mapper.exe
